### ISSUE TITLE
NDEX account support

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape-explore#11]
TODO -- edit me

**Comment by maxkfranz** [comment]
@jingjingbic, I'll leave this for you to spec out since you have a better sense of the existing login system.

**Comment by dotasek** [comment]
The login mechanism should allow the user to login using either:

- An explicit username/password for an NDEx account
- A google account authorization

**Comment by dotasek** [comment]
There are a few existing components that have been refactored into a re-usable library for this:

https://github.com/idekerlab/ce-components/tree/ce-contexts

They use react hooks to manage login state and provide user information for other components in a React App.
