### ISSUE TITLE
Better scaling of synchronization events.

### ISSUE THREAD

**Issue by mikekucera** [cytoscape/cytoscape-explore#111]
**Description of new feature**

- Some kind of batching/throttling/debouncing of the events that are used to synchronize a network.

**Motivation for new feature**

Open the same network twice in two separate browser windows (something the size of galFiltered). Arrange the windows next to each other so you can see both networks at the same time. In the first window run a layout, and start playing with the layout sliders. Watch as the second window struggles to keep up.

**Comment by maxkfranz** [comment]
Angles to consider:

- Actual sync cycle
- Perception
- Animation coordination

**Comment by maxkfranz** [comment]
Closing via #129.  Let's use new issues for any particular problems we notice in future
