### ISSUE TITLE
Share button

### ISSUE THREAD

**Issue by mikekucera** [cytoscape/cytoscape-explore#112]
**Description of new feature**

A standard share button. Used to send a link to the network to someone else, or copy a link to the clipboard.

**Motivation for new feature**

Very common feature these days. Makes it very clear that one of the major advantages of Cytoscape-on-the-web is the ability to share networks and collaborate with others.

**Comment by maxkfranz** [comment]
See also https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share
