### ISSUE TITLE
Slide out side panel

### ISSUE THREAD

**Issue by mikekucera** [cytoscape/cytoscape-explore#113]
**Description of new feature**

Make it possible to hide the side panel. Probably animate the panel so it slides in and out.

**Motivation for new feature**

Gives the user more screen real-estate to see their network.

**Comment by maxkfranz** [comment]
Design notes:

- Common to use caret icons for this -- and they wouldn't conflict with the edge arrow style icon.  A simple way to add support would be for a tool item icon to be a caret or carets that toggle the sidebar.
- It's probably best not to toggle the sidebar completely.  The user would benefit from having the tool icons still visible even when the sidebar is hidden
