### ISSUE TITLE
Editable network title

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape-explore#2]
Implement the editable network title:

- [ ] The title is at the top of the screen.
- [ ] Show border of text box only on hover or focus
- [ ] Save the title under `cy.data('title')`

![Screen Shot 2019-06-06 at 1 06 54 PM](https://user-images.githubusercontent.com/989043/59052009-1f006880-885c-11e9-9963-1d6eb93193c6.png)

[Full PDF mockup](https://drive.google.com/open?id=16sNONhFxO-ryBj6HVtOqA-agxJIkU2n5)

**Comment by chrtannus** [comment]
We should save it under `cy.data('name')` instead, because that's what Cy3 does and we already look into the 'name' attribute to show the header's title.
