### ISSUE TITLE
Import a network from Cy3

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape-explore#20]
- [x] Import a network via JSON and Cy REST as a prototype
- [ ] Import via CX once it's supported in Cy3

**Comment by keiono** [comment]
We need more details for this function.  Should this file-based?  Or via CyREST API?

**Comment by maxkfranz** [comment]
Another alternative to consider is an export option within Cy3 UI to CE.  There, you have the advantage of being able to more easily select which network to use within the session.  

Overall, there may be three approaches:

(1) Export from Cy3 UI to CE.

(2) Upload a file, supported in Cy3, within CE (e.g. by drag and drop).

(3) Import a network via CyREST.

Whereas (1) and (3) are similar in that you need to have Cy3 open, (2) is more unique.  I suspect that when doing an export a user will tend to start with the source app rather than the target app, so (1) may be more natural than (3).  In the longterm, we might end up supporting all three approaches.

Approach (3) may be the most tractable option to start with.
