### ISSUE TITLE
Export to NDEX

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape-explore#23]
Export function is essentially a _Save_ feature for CE.  It should support:

- Save (create new entry in the user's NDEx account)
- Save as (Overwrite existing entry)

**Comment by keiono** [comment]
Need to decide what kind of network data model is used in the application.  (Cytoscape.js?)

**Comment by maxkfranz** [comment]
In practice, there may be multiple view models in the UI that could be converted to CX (e.g. Cy JSON for the small-scale renderer, perhaps ccNetViz JSON for the large-scale renderer).
