### ISSUE TITLE
M1 Deployment

### ISSUE THREAD

**Issue by dotasek** [cytoscape/cytoscape-explore#65]
Our deployment must be defined and implemented.

Ideally, this should be done with Continuous Integration, so that GitHub activities can be used to automatically release new versions.

Sub-Tasks:

- [x] Dockerize Front End and CouchDB
- [x] Pick Continuous Integration provider

**Comment by maxkfranz** [comment]
See the feature/docker branch for WIP Docker support re. deployment: https://github.com/cytoscape/cytoscape-explore/tree/feature/docker

**Comment by dotasek** [comment]
Deployment is live and available [here] (http://cytoexplore-dev.ucsd.edu:12345/document/demo)

Information about continuous deployment is documented internally for developers.
